version: "3.3"

services:

    db:
      restart: 'always'
      image: mariadb:10.4
      command: 'mysqld --character-set-server=utf8 --collation-server=utf8_general_ci'
      working_dir: /code
      environment:
        MYSQL_ROOT_PASSWORD: liyi
        MYSQL_DATABASE: drugref2
        MYSQL_USER: oscar
        MYSQL_PASSWORD: oscar
      volumes:
        # TODO: capture changes made in prod.
        - ./conf/my.cnf:/etc/mysql/my.cnf
        # TODO: build some scripts in so we need not mount everything.
        - .:/code
        - mariadb-files:/var/lib/mysql
      networks:
        - back-tier
    tomcat_oscar:
      restart: 'always'
      image: openosp/open-osp:latest
      build:
        context: .
        dockerfile: docker/tomcat_oscar/Dockerfile
      volumes:
        - ./volumes/oscar.properties:/root/oscar.properties
        - ./OscarDocument:/var/lib/OscarDocument/
        - ./conf/ssl.crt:/usr/local/tomcat/conf/ssl.crt
        - ./conf/ssl.key:/usr/local/tomcat/conf/ssl.key
        # TODO: does this really need to be customizable?
        - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
        # - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
        # TODO: does this really need to be customizable?       
        - ./drugref2.properties:/root/drugref2.properties
      networks:
        - back-tier
      environment:
        TZ: America/Vancouver
    

volumes:
  mariadb-files:
    driver: local

networks:
  back-tier:
    driver: bridge


