version: "3.3"

services:

    db:
      restart: 'always'
      image: mariadb:10.4
      command: 'mysqld --character-set-server=utf8 --collation-server=utf8_general_ci'
      working_dir: /code
      env_file: 
        - local.env
      environment:
        MYSQL_DATABASE: drugref2
        MYSQL_USER: oscar
      volumes:
        # TODO: build this in to the image.
        - ./docker/db/my.cnf:/etc/mysql/my.cnf
        # TODO: build some scripts in so we need not mount everything.
        - .:/code
        - mariadb-files:/var/lib/mysql
      networks:
        - back-tier

    oscar:
      restart: 'always'
      image: openosp/open-osp:latest
      build: docker/oscar
      volumes:
        - ./volumes/oscar.properties:/root/oscar.properties
        - ./volumes/drugref2.properties:/root/drugref2.properties
        - ./volumes/OscarDocument:/var/lib/OscarDocument
        - ./volumes/ssl.crt:/usr/local/tomcat/conf/ssl.crt
        - ./volumes/ssl.key:/usr/local/tomcat/conf/ssl.key
        # Add other volumes to the volumes/ folder, and mount them via docker-compose.override.yml
      networks:
        - back-tier
      environment:
        TZ: America/Vancouver  
        
    expedius:
      restart: 'always'
      image: openosp/expedius:latest
      build: docker/expedius
      volumes:
        - ./volumes/ssl.crt:/usr/local/tomcat/conf/ssl.crt
        - ./volumes/ssl.key:/usr/local/tomcat/conf/ssl.key
        - ./volumes/expedius:/var/lib/expedius
        - ./volumes/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      networks:
        - back-tier
      environment:
        TZ: America/Vancouver
        
    faxws:
      restart: 'always'
      image: openosp/faxws:latest
      build: docker/faxws
      volumes:
        - ./volumes/OscarDocument:/var/lib/OscarDocument
        - ./volumes/ssl.crt:/usr/local/tomcat/conf/ssl.crt
        - ./volumes/ssl.key:/usr/local/tomcat/conf/ssl.key
        - ./volumes/faxws.properties:/root/faxws.properties
        - ./volumes/faxws-context.xml:/usr/local/tomcat/Catalina/faxWs/context.xml
      networks:
        - back-tier
      env_file:
        - local.env
      environment:
        TZ: America/Vancouver
        MYSQL_HOST: db
        
volumes:
  mariadb-files:
    driver: local

networks:
  back-tier:
    driver: bridge


