version: "3.3"

services:
    builder:
      image: openjdk:8
      volumes:
        - .:/code
        - $HOME/.m2:/root/.m2
      working_dir: /code
      command: ./build.sh
      environment:
        - OSCAR_TREEISH
        - OSCAR_REPO

    db:
      restart: 'always'
      image: mariadb:10.4
      command: 'mysqld --character-set-server=utf8 --collation-server=utf8_general_ci'
      working_dir: /code
      environment:
        MYSQL_ROOT_PASSWORD: liyi
        MYSQL_DATABASE: oscar_mcmaster
        MYSQL_USER: oscar
        MYSQL_PASSWORD: oscar
      volumes:
        - ./dbdump:/docker-entrypoint-initdb.d
        - ./conf/my.cnf:/etc/mysql/my.cnf
        - .:/code
        - mariadb-files:/var/lib/mysql
      networks:
        - back-tier
    tomcat_oscar:
      restart: 'always'
      image: openosp/open-osp
      build: .
      volumes:
#        - ./oscar.war:/usr/local/tomcat/webapps/oscar_mcmaster.war
#        - ./conf/logging.properties:/usr/local/tomcat/conf/logging.properties
#        - ./conf/logging-servlet.properties:/usr/local/tomcat/conf/logging-servlet.properties
#        - ./conf/oscar_mcmaster.properties:/root/oscar_mcmaster.properties
#        - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
#        - ./drugref2.war:/usr/local/tomcat/webapps/drugref2.war
#        - ./conf/drugref2.properties:/root/drugref2.properties

#        - ./spring-instrument-3.2.9.RELEASE.jar:/spring-instrument-3.2.9.RELEASE.jar

#      environment:
#        - CATALINA_OPTS="-javaagent:/spring-instrument-3.2.9.RELEASE.jar"
      networks:
        - back-tier

volumes:
  mariadb-files:
    driver: local

networks:
  back-tier:
    driver: bridge


