version: "3.3"

services:
  nginx:
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./conf/ssl:/ssl
      - ./conf/nginx/conf.d/dev.conf:/etc/nginx/conf.d/oscar.template

  backup:
    build: .
    image: countable/s3-backup-job:1.0
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BACKUP_BUCKET=countable/backups
      - BACKUP_CMD='mysqldump -uroot -pliyi oscar_mcmaster > dump'
    restart: always