version: "3.3"

services:

    db:
      restart: 'always'
      image: mariadb:10.4
      command: 'mysqld --character-set-server=utf8 --collation-server=utf8_general_ci'
      working_dir: /code
      environment:
        MYSQL_ROOT_PASSWORD: liyi
        MYSQL_DATABASE: drugref2
        MYSQL_USER: oscar
        MYSQL_PASSWORD: oscar
      volumes:
        - ./conf/my.cnf:/etc/mysql/my.cnf
        - .:/code
        - mariadb-files:/var/lib/mysql
      networks:
        - back-tier
    tomcat_oscar:
      restart: 'always'
      image: openosp/open-osp:latest
      build: .
      volumes:
#        - ./conf/logging.properties:/usr/local/tomcat/conf/logging.properties
#        - ./conf/logging-servlet.properties:/usr/local/tomcat/conf/logging-servlet.properties
        - ./oscar.properties:/root/oscar.properties
        - ./OscarDocument:/var/lib/OscarDocument/
        - ./conf/ssl.crt:/usr/local/tomcat/conf/ssl.crt
        - ./conf/ssl.key:/usr/local/tomcat/conf/ssl.key
        - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
#        - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
        - ./drugref2.properties:/root/drugref2.properties
      networks:
        - back-tier
      environment:
        TZ: America/Vancouver
    nginx:
      restart: 'always'
      image: nginx:latest
      networks:
        - back-tier
      volumes:
        - ./static:/static
      env_file:
        - oscar-login.env
      command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/oscar.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    

volumes:
  mariadb-files:
    driver: local

networks:
  back-tier:
    driver: bridge


