version: "3.3"

services:
    builder:
      image: openjdk:8
      volumes:
        - .:/code
        - $HOME/.m2:/root/.m2
      working_dir: /code
      command: ./build.sh
      environment:
        - OSCAR_BRANCH
        - OSCAR_REPO

    db:
      restart: 'always'
      image: mariadb:10.4
      command: 'mysqld --character-set-server=utf8 --collation-server=utf8_general_ci'
      working_dir: /code
      environment:
        MYSQL_ROOT_PASSWORD: liyi
        MYSQL_DATABASE: oscar_mcmaster
        MYSQL_USER: oscar
        MYSQL_PASSWORD: oscar
      volumes:
        - ./dbdump:/docker-entrypoint-initdb.d
        - ./conf/my.cnf:/etc/mysql/my.cnf
        - .:/code
        - mariadb-files:/var/lib/mysql
      networks:
        - back-tier
    tomcat_oscar:
      restart: 'always'
      build: .
      volumes:
        - ${OSCAR_WAR}:/usr/local/tomcat/webapps/oscar_mcmaster.war
        - ./conf/logging.properties:/usr/local/tomcat/conf/logging.properties
        - ./conf/logging-servlet.properties:/usr/local/tomcat/conf/logging-servlet.properties
#    - ./conf/oscar_mcmaster_bc.properties:/usr/share/tomcat/oscar_mcmaster.properties
        - ./conf/oscar_mcmaster_bc.properties:/root/oscar_mcmaster.properties
        - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      networks:
        - back-tier

volumes:
  mariadb-files:
    driver: local

networks:
  back-tier:
    driver: bridge


