version: "3.3"

services:

    db:
      restart: 'always'
      image: mariadb:10.4
      command: 'mysqld --character-set-server=utf8 --collation-server=utf8_general_ci'
      working_dir: /code
      environment:
        MYSQL_ROOT_PASSWORD: liyi
        MYSQL_DATABASE: drugref2
        MYSQL_USER: oscar
        MYSQL_PASSWORD: oscar
      volumes:
        # TODO: build this in to the image.
        - ./docker/db/my.cnf:/etc/mysql/my.cnf
        # TODO: build some scripts in so we need not mount everything.
        - .:/code
        - mariadb-files:/var/lib/mysql
      networks:
        - back-tier
    tomcat_oscar:
      restart: 'always'
      image: openosp/open-osp:latest
      build: docker/tomcat_oscar
      volumes:
        - ./volumes/oscar.properties:/root/oscar.properties
        - ./volumes/OscarDocument:/var/lib/OscarDocument
        - ./volumes/ssl.crt:/usr/local/tomcat/conf/ssl.crt
        - ./volumes/ssl.key:/usr/local/tomcat/conf/ssl.key
        # Add other volumes to the volumes/ folder, and mount them via docker-compose.override.yml
      networks:
        - back-tier
      environment:
        TZ: America/Vancouver  
    tomcat_expedius:
      restart: 'always'
      image: openosp/expedius:latest
      build: docker/tomcat_expedius
      volumes:
        - ./volumes/expedius:/var/lib/expedius
      networks:
        - back-tier
      environment:
        TZ: America/Vancouver
volumes:
  mariadb-files:
    driver: local

networks:
  back-tier:
    driver: bridge


