version: '3'

services:
    builder:
      image: openjdk:8
      volumes:
        - .:/code
        - $HOME/.m2:/root/.m2
      working_dir: /code
      command: ./build-release.sh
      environment:
        - OSCAR_TREEISH
        - OSCAR_REPO

