version: '3'

services:
    builder:
      image: openjdk:8
      volumes:
        - .:/code
        - $HOME/.m2:/root/.m2
      working_dir: /code
      command: ./build-release.sh
      environment:
        - OSCAR_TREEISH
        - OSCAR_REPO
    nginx:
      restart: 'always'
      image: nginx:latest
      networks:
        - back-tier
      volumes:
        - ./static:/static
        - ./conf/ssl.crt:/ssl/ssl.crt
        - ./conf/ssl.key:/ssl/ssl.key
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/oscar.template
      env_file:
        - local.env
      command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/oscar.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  back-tier:
    driver: bridge

